services:

  mysql:
    image: 'mysql'
    environment:
      - 'MYSQL_PASSWORD=root'
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_DATABASE=banco_de_sangue'
      - TZ=America/Sao_Paulo
    volumes:
      - /opt/mysql:/opt/lib/mysql
      - /opt/mysql/banco_de_sangue_sql.sql:/docker-entrypoint-initdb.d/banco_de_sangue_sql.sql
    ports:
      - '3306:3306'
    networks:
      - banco-de-sangue-network

  api-banco-de-sangue:
    restart: on-failure
    depends_on:
      - mysql
    image: 'alexandreluchetti/api-banco-de-sangue:1.0.0'
    ports:
      - '8080:8080'
    volumes:
      - /opt/api-banco-de-sangue:/opt/lib/api-banco-de-sangue
    environment:
      - TZ=America/Sao_Paulo
      - 'SPRING_CONFIG_LOCATION=classpath:application.yml'
      - 'SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/banco_de_sangue'
      - 'SPRING_DATASOURCE_USERNAME=root'
      - 'SPRING_DATASOURCE_PASSWORD=root'
    networks:
      - banco-de-sangue-network

  angular-banco-de-sangue:
    restart: on-failure
    depends_on:
      - mysql
      - api-banco-de-sangue
    image: 'alexandreluchetti/angular-banco-de-sangue:1.0.0'
    ports:
      - '4200:4200'
    volumes:
      - /opt/angular-banco-de-sangue:/opt/lib/angular-banco-de-sangue
    environment:
      - TZ=America/Sao_Paulo
    networks:
      - banco-de-sangue-network

networks:
  banco-de-sangue-network:
    driver: bridge
  java-network:
    external: true