server:
  port: 8303

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

database:
  jdbcUrl: jdbc:mysql://mysql:3306/banco_de_sangue
  username: root
  password: root
  driver-class-name: com.mysql.cj.jdbc.Driver
